### ISSUE TITLE
[Feature Reques] select bookmark from list

### ISSUE THREAD

**Issue by FedericoCalzoni** [gregorias/bookmarks.fish#2]
I think it would be nice to have the possibility to choose the bookmark from the list. 

An example usage could be that if no arguments are provided when bf go is executed (or even only bf) a numbered list of the bookmark is proposed, and waits for the input of the user. 
In the example below, the user writes bf go, the numbered list is shown, the user selects 2, and it is prompted to the second path.  

```shell
~ bf go
1) bookmark1     'saved/path/to/bookmark1'
2) bookmark2     'saved/path/to/bookmark2'

Select bookmark number: 2
~/saved/path/to/bookmark2/  
```

**Comment by gregorias** [comment]
Sounds alright, but there’s already built-in completion that gives you a list of available bookmarks. Why isn’t that enough?

**Comment by FedericoCalzoni** [comment]
You are right, I haven't thought about it.
